name: Build Kernels

on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'Kernel variant to build'
        required: true
        default: 'All variants'
        type: choice
        options:
          - All variants
          - KSU

jobs:
  build_ksu:
    name: Build KSU Kernel
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.variant == 'All variants' || github.event.inputs.variant == 'KSU' }}
    
    steps:
      - name: Checkout DΛG branch
        uses: actions/checkout@v4
        with:
          ref: 'DΛG'

      - name: Download Apache Arrow's util_free_space.sh
        run: |
          curl -L -o util_free_space.sh https://raw.githubusercontent.com/apache/arrow/main/ci/scripts/util_free_space.sh
          chmod +x util_free_space.sh
          ./util_free_space.sh

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils \
          default-jdk git gnupg flex bison gperf build-essential zip curl libc6-dev libncurses-dev libx11-dev libreadline-dev libgl1 libgl1-mesa-dev \
          python3 make sudo gcc g++ bc grep tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev python-is-python3 libc6-dev libtinfo6 \
          make repo cpio kmod openssl libelf-dev pahole libssl-dev libarchive-tools zstd rsync --fix-missing && \
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && \
          sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb && \
          rm libtinfo5_6.3-2ubuntu0.1_amd64.deb
      
      - name: Make directories
        run: |
          mkdir -p $HOME/kernel
          mkdir -p $HOME/toolchain
          mkdir -p $HOME/toolchain/clang-r450784c

      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: $HOME/toolchain/clang-r450784c
          key: clang-r450784c-toolchain

      - name: Fetch toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          wget -c https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/llvm-r450784/clang-r450784c.tar.gz -O clang.tar.gz
          tar -xf clang.tar.gz -C $HOME/toolchain/clang-r450784c && rm -rf clang.tar.gz
        
      - name: Fetch AnyKernel3
        run: |
          git clone --branch a54x https://github.com/daglaroglou/AnyKernel3.git $HOME/AnyKernel3

      - name: Fetch kernel source
        run: |
          git clone https://github.com/daglaroglou/android_kernel_samsung_a54x $HOME/kernel

      - name: Login actions bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Import KernelSU driver
        run: |
          cd $HOME/kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Set config variables for KernelSU
        run: |
          cd $HOME/kernel
          ./scripts/config --file arch/arm64/configs/custom.config \
            --enable CONFIG_KSU

      - name: Set config variables for Mountify
        run: |
          cd $HOME/kernel
          ./scripts/config --file arch/arm64/configs/custom.config \
            --enable CONFIG_TMPFS_XATTR \
            --enable CONFIG_TMPFS_POSIX_ACL

      - name: Set config variable for Localversion
        run: |
          cd $HOME/kernel
          ./scripts/config --file arch/arm64/configs/custom.config \
            --set-str CONFIG_LOCALVERSION "-DΛG-KSU" \
            --set-val CONFIG_LOCALVERSION_AUTO n

      - name: Build kernel
        run: |
          cd $HOME/kernel
          export PATH="$HOME/toolchain/clang-r450784c/bin:$PATH"
          export CONFIGS="a54x_defconfig custom.config"
          export KERNEL_DIR=$HOME/kernel
          export KBUILD_BUILD_HOST="Github-Actions"
          export KBUILD_BUILD_USER="daglaroglou"
          export PLATFORM_VERSION=16
          export TARGET_SOC=s5e8835
          export DEPMOD=depmod
          MAKE_PARAMS="-j$(nproc --all) ARCH=arm64 KBUILD_OUTPUT=$HOME/kernel/out CC=clang LLVM=1 LLVM_IAS=1 CLANG_TRIPLE=llvm- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-"
          make $MAKE_PARAMS $CONFIGS
          make $MAKE_PARAMS

      - name: Extract version info
        run: |
          cd $HOME/kernel
          LOCALVERSION=$(grep "CONFIG_LOCALVERSION=" arch/arm64/configs/custom.config | cut -d'=' -f2 | tr -d '"')
          echo "LOCALVERSION=$LOCALVERSION" >> $GITHUB_ENV
          KERNEL_NAME_RAW="${LOCALVERSION#-}"
          KERNEL_NAME_RELEASE="${KERNEL_NAME_RAW//Λ/A}"
          echo "KERNEL_NAME=$KERNEL_NAME_RELEASE" >> $GITHUB_ENV

      - name: Verify kernel build
        run: |
          if [ ! -f "$HOME/kernel/out/arch/arm64/boot/Image" ]; then
            echo "Error: Kernel Image not found!"
            exit 1
          fi
          echo "Kernel build successful!"

      - name: Create zip
        run: |
          cd $HOME/AnyKernel3
          cp $HOME/kernel/out/arch/arm64/boot/Image $HOME/AnyKernel3/
          7z a "${{ env.KERNEL_NAME }}.zip" . -xr!*.git*

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/AnyKernel3/*.zip
          name: DΛG Kernels - ${{ env.DATE }}
          tag_name: "${{ env.DATE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

  build_ksu_susfs:
    name: Build KSU-SUSFS Kernel
    needs: [notify-start]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.variant == 'All variants' || github.event.inputs.variant == 'KSU-SUSFS' }}
    
    steps:
      - name: Checkout DΛG branch
        uses: actions/checkout@v4
        with:
          ref: 'DΛG'

      - name: Download Apache Arrow's util_free_space.sh
        run: |
          curl -L -o util_free_space.sh https://raw.githubusercontent.com/apache/arrow/main/ci/scripts/util_free_space.sh
          chmod +x util_free_space.sh
          ./util_free_space.sh

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils \
          default-jdk git gnupg flex bison gperf build-essential zip curl libc6-dev libncurses-dev libx11-dev libreadline-dev libgl1 libgl1-mesa-dev \
          python3 make sudo gcc g++ bc grep tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev python-is-python3 libc6-dev libtinfo6 \
          make repo cpio kmod openssl libelf-dev pahole libssl-dev libarchive-tools zstd rsync --fix-missing && \
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && \
          sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb && \
          rm libtinfo5_6.3-2ubuntu0.1_amd64.deb
      
      - name: Make directories
        run: |
          mkdir -p $HOME/kernel
          mkdir -p $HOME/toolchain
          mkdir -p $HOME/toolchain/clang-r450784c

      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: $HOME/toolchain/clang-r450784c
          key: clang-r450784c-toolchain

      - name: Fetch toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          wget -c https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/llvm-r450784/clang-r450784c.tar.gz -O clang.tar.gz
          tar -xf clang.tar.gz -C $HOME/toolchain/clang-r450784c && rm -rf clang.tar.gz
        
      - name: Fetch AnyKernel3
        run: |
          git clone --branch a54x https://github.com/daglaroglou/AnyKernel3.git $HOME/AnyKernel3

      - name: Fetch kernel source
        run: |
          git clone https://github.com/daglaroglou/android_kernel_samsung_a54x $HOME/kernel

      - name: Login actions bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Import KernelSU driver
        run: |
          cd $HOME/kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Set config variables for KernelSU
        run: |
          cd $HOME/kernel
          ./scripts/config --file arch/arm64/configs/custom.config \
            --enable CONFIG_KSU
      
      - name: Import SUSFS
        run: |
          cd $HOME
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android13-5.15

      - name: Fetch kernel patches
        run: |
          cd $HOME
          git clone https://github.com/daglaroglou/a54x_kernel_patches.git

      - name: Copy SUSFS files
        run: |
          cd $HOME/susfs4ksu
          cp kernel_patches/50_add_susfs_in_gki-android13-5.15.patch $HOME/kernel/
          cp kernel_patches/fs/* $HOME/kernel/fs/
          cp kernel_patches/include/linux/* $HOME/kernel/include/linux/
          cp kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch $HOME/kernel/KernelSU/

      - name: Copy kernel patches
        run: |
          cd $HOME/a54x_kernel_patches
          cp susfs/2.0.0/* $HOME/kernel/

      - name: Apply patches
        run: |
          set +e
          cd $HOME/kernel
          patch -p1 < 50_add_susfs_in_gki-android13-5.15.patch
          patch -p1 < exec.patch
          patch -p1 < namespace.patch
          patch -p1 < base.patch
          cd KernelSU
          patch -p1 < 10_enable_susfs_for_ksu.patch
          set -e

      - name: Set config variables for SUSFS
        run: |
          cd $HOME/kernel
          ./scripts/config --file arch/arm64/configs/custom.config \
            --enable CONFIG_KSU_SUSFS \
            --enable CONFIG_KSU_SUSFS_SUS_PATH \
            --enable CONFIG_KSU_SUSFS_SUS_MOUNT \
            --enable CONFIG_KSU_SUSFS_SUS_KSTAT \
            --enable CONFIG_KSU_SUSFS_SPOOF_UNAME \
            --enable CONFIG_KSU_SUSFS_ENABLE_LOG \
            --enable CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS \
            --enable CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG \
            --enable CONFIG_KSU_SUSFS_OPEN_REDIRECT

      - name: Set config variables for Mountify
        run: |
          cd $HOME/kernel
          ./scripts/config --file arch/arm64/configs/custom.config \
            --enable CONFIG_TMPFS_XATTR \
            --enable CONFIG_TMPFS_POSIX_ACL

      - name: Set config variable for Localversion
        run: |
          cd $HOME/kernel
          ./scripts/config --file arch/arm64/configs/custom.config \
            --set-str CONFIG_LOCALVERSION "-DΛG-KSU_SUSFS" \
            --set-val CONFIG_LOCALVERSION_AUTO n

      - name: Build kernel
        run: |
          cd $HOME/kernel
          export PATH="$HOME/toolchain/clang-r450784c/bin:$PATH"
          export CONFIGS="a54x_defconfig custom.config"
          export KERNEL_DIR=$HOME/kernel
          export KBUILD_BUILD_HOST="Github-Actions"
          export KBUILD_BUILD_USER="daglaroglou"
          export PLATFORM_VERSION=16
          export TARGET_SOC=s5e8835
          export DEPMOD=depmod
          MAKE_PARAMS="-j$(nproc --all) ARCH=arm64 KBUILD_OUTPUT=$HOME/kernel/out CC=clang LLVM=1 LLVM_IAS=1 CLANG_TRIPLE=llvm- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-"
          make $MAKE_PARAMS $CONFIGS
          make $MAKE_PARAMS

      - name: Extract version info
        run: |
          cd $HOME/kernel
          LOCALVERSION=$(grep "CONFIG_LOCALVERSION=" arch/arm64/configs/custom.config | cut -d'=' -f2 | tr -d '"')
          echo "LOCALVERSION=$LOCALVERSION" >> $GITHUB_ENV
          KERNEL_NAME_RAW="${LOCALVERSION#-}"
          KERNEL_NAME_RELEASE="${KERNEL_NAME_RAW//Λ/A}"
          echo "KERNEL_NAME=$KERNEL_NAME_RELEASE" >> $GITHUB_ENV

      - name: Verify kernel build
        run: |
          if [ ! -f "$HOME/kernel/out/arch/arm64/boot/Image" ]; then
            echo "Error: Kernel Image not found!"
            exit 1
          fi
          echo "Kernel build successful!"

      - name: Create zip
        run: |
          cd $HOME/AnyKernel3
          cp $HOME/kernel/out/arch/arm64/boot/Image $HOME/AnyKernel3/
          7z a "${{ env.KERNEL_NAME }}.zip" . -xr!*.git*

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/AnyKernel3/*.zip
          name: DΛG Kernels - ${{ env.DATE }}
          tag_name: "${{ env.DATE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
